server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 20000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ???
    password: ???
    url: jdbc:mysql://127.0.0.1/online_exercise_test?useUnicode=true&characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #连接池初始化大小
      initial-size: 1
      #最大连接数量
      max-active: 500
      #最小连接数
      min-idle: 1
      #超时等待时间以毫秒为单位 6000毫秒/1000等于60秒
      max-wait: 60000

  redis:
    host: 127.0.0.16
    port: 6400
    password: p
    timeout: 3000
    database: 0
    jedis:
      pool:
        #最大连接数
        max-active: 30
        #最大空闲时间
        max-idle: 10

  mail:
    host: smtp.163.com
    username: fdsjoignlk@163.com
    password: jboifag.biu
    properties:
      mail:
        smtp:
          auth: true
          timout: 25000

  jackson:
    #为null时jackson不会将其序列化
    default-property-inclusion: non_null
  jersey:
    application-path: /rest
  session:
    store-type: redis

#是否开启 swagger-ui
swagger:
  enabled: true

exercise:
  timeout:
    redis: 120
    mail: 10
    sms: 5
  wechat:
    appId: ???
    appSecret: ???
